apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-ns

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: jenkins-ns
  name: jenkins

--- 

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-cluster-admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  namespace: jenkins-ns
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
